### ISSUE TITLE
Implement Kafka protocol

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#467]
## **Summary**
Implementation of Kafka protocol in Memphis

## **Value**
To enable Kafka users to easily work with Memphis without changing their code, Memphis will support Kafka protocol

## **Persona(s)**
- Data Engineers
- Developers
- Kafka users
- New Users

**Comment by g41797** [comment]
Hi
As far as I understand Q4 is target 
I'd like to check possibility to participate

**Comment by yanivbh1** [comment]
Hey @g41797 ,
Thank you for your interest in contributing to Memphis!
As this feature is highly critical and should be greatly planned before, it would be great to also have more direct communication through our [discord](https://memphis.dev/discord)
Please let me know once your there, I will create a shared channel for us, and we will discuss the initial planning alongside @idanasulinmemphis

**Comment by g41797** [comment]
on board

**Comment by g41797** [comment]
Implementation of Kafka protocol in Memphis - client point of view
- Network protocol TCP
- Encryption - No
- _Subset_ of [APIs](https://kafka.apache.org/documentation/#api)
- Kafka Client SDKs/libraries (installation,usage, configuration,tutorials)
- Memphis-Kafka documentation 

Last is most important. It will help us to understand expectations of users and as result what we actually should to implement. I don't know exactly, but if Kafka and Memphis use different terminology (possibly for the same things) - explanation is the part of this doc. How will co-exist kafka-memphis and memhpis on the client side. Do we have some recommendations? 

Simultaneously we need to look for ready solutions 
e.g we know that go code will parse binary data with Kafka messages 
how to simplify this process?
[Redpanda](https://github.com/redpanda-data/redpanda/tree/dev/src/v/kafka/protocol/schemata) uses JSON schema files for  [generation](https://github.com/redpanda-data/redpanda/blob/dev/src/v/kafka/protocol/schemata/generator.py) of c code

[franz-go](https://github.com/twmb/franz-go/tree/master/generate/definitions) uses proprietary format for generation of go code. 

May be mix of these solutions will be good idea?

**Comment by g41797** [comment]
of course , I talked about code-generation just as part of brainstorming

as far as I understand dashboard is bestselling point of Memphis
how Kafka producers/consumers shown ? are there any difference? is it fully transparent? messages from Kafka producer may be consumed be memphis consumer etc
need smaltalk whatsapp/phone doesn't matter 

regarding implementation

we are not talking about adapter on the client side, because in this case we need to support  go, js, pyton etc a lot of works

"directly within the core" - best solution for performance but not in the early stage (stability etc)
separated adapter process looks better on this stage

as example of similar solution see [nats-kafka](https://github.com/nats-io/nats-kafka)

**Comment by idanasulinmemphis** [comment]
@g41797 client-side solution is indeed the worst option.
An adapter might cause a very poor performance what do you think will be the impact? also in terms of ordering and reliability (like ack etc.)

**Comment by idanasulinmemphis** [comment]
Totally agree, let's start from that part I'd say, after approving it we will be able to move forward. What do you think?

**Comment by g41797** [comment]
as old-fashioned man I think we need to talk

**Comment by yanivbh1** [comment]
Feature is being managed in issue #849
