### ISSUE TITLE
Bug: In station creation flow can cause stale streams

### ISSUE THREAD

**Issue by OrMemphis** [memphisdev/memphis#579]
### Describe the bug

If while a station is being created, an error occurs with writing the station to the DB, we'll have a stale stream.

currently, we garbage-collect only stale stations from the DB, but not streams.

We currently have a garbage collector background task (zombie resources), so we want to add this process into it.

### Steps to reproduce

Create a new station and intentionally prevent the station from being stored in the DB. You will end with a stream but with no Station.

### Affected services

Broker

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by danielsinai** [comment]
Hi :) (new here)
Just curious about the desired solution

I guess we don't want to check that the record got successfully inserted to the database and just then create the stream, or delete the stream if something after inserting - due to the ideal that the metadata store will not make any administration operation fail.

If that's true - what is the solution you want to implement at the `memphis_zombie_resources` - would you just want to delete the station? it feels the same as validating it at insertion time.
Or you want to have a retry mechanism that will try to create it inside the db instead?

**Comment by idanasulinmemphis** [comment]
I believe that rolling back and deleting the stream in case of station fails from being stored on the metadata storage is best, as your suggestion

**Comment by danielsinai** [comment]
> deleting the stream in case of station fails from being stored on the 

Wouldn't it be just easier to validate it inserted to the DB successfully in insertion at memphis_starions_handlers.go on createStation function?

If so I can open up a PR soon

**Comment by idanasulinmemphis** [comment]
Yes sure that is exactly what I meant

**Comment by danielsinai** [comment]
Opened up a PR #843, I see there is no tests on PR open - how can I run the tests to validate I didn't break anything? :)

**Comment by idanasulinmemphis** [comment]
@danielsinai I tested it up and it works fine
